<?php
require_once("input_upload_img.php");
require_once("input_faille_xss.php");
require_once("input_name.php");
require_once("textarea_description.php");
require_once("input_genre.php");
require_once("input_note.php");
require_once("input_pegi.php");
require_once("input_plateform.php");
require_once("input_price.php");
